### ISSUE TITLE
General Question - Static site generation from NixOS Configuration

### ISSUE THREAD

**Issue by Joaqim** [mynixos/support#11]
Firstly, **MyNixOS** has been a tremendous help for learning the **NixOS** ecosystem without necessarily diving deep into the Nix language ( though I have benefited greatly from learning Nix and Flakes even outside of **NixOS**. )

I'm looking to generate a website from my personal **NixOS** configuration, similar to: [`My Literal Emacs configuration`](https://github.com/renzmann/.emacs.d/tree/main), in which the Elisp code for configuring Emacs is tangled directly inside the `README.md` which is then also used to generate a static website ( there are already plenty of tools to generate html from Markdown. )
### Question
**Are you aware of any open source projects that parses NixOS configurations to create static sites similar to yours?**

In my admittedly brief searching I haven't found such a thorough project as **MyNixOS** - in fact, I would have expected there to be a lot more projects that utilizes the thorough Nix type declarations of possible `packages` and `options`.

 For me so far, **MyNixOS** is only missing the collaborative nature of GitHub with `README.md`, `commits`, `branches`, `pull requests` and `issues`.
 Even just commenting individual `modules` would go a long way.

**Comment by pveierland** [comment]
Hi Joaqim! Thank you for the kind feedback.

The use-case you describe is very similar to what is a goal for MyNixOS - being able to create and share a more literal and re-usable configuration set that is also reproducible - such that a single source of truth is used to the greatest extent within the configuration / documentation.

I'm not aware of any open source projects that parses NixOS configurations to create static sites in a general manner. A continuation of MyNixOS 2.0 is in the planning phase that would seek to solve the collaboration aspect by moving to using Nix as the direct configuration representation instead of using an internal format that is compiled to Nix. I'll keep your ideas for static site generation in mind for the planning of this.
