### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by CallMeCaleb94** [mynixos/support#20]
Trying to build my home media server and was unable to find the `jellyfin-ffmpeg` package when adding packages through the outputs menu
![Screenshot_20241118_130420](https://github.com/user-attachments/assets/6fc794c5-c216-4f6c-9922-881ad75e39ad)
![Screenshot_20241118_130323](https://github.com/user-attachments/assets/ad82d83d-b3f7-47e3-a93c-a0dea52fbf17)

**Comment by pveierland** [comment]
It appears that this issue is caused by the platform metadata missing for the `jellyfin-ffmpeg` package, which causes it to not be shown because of the `x86_64-linux` search filter set by the NixOS configuration. A workaround is to add the `jellyfin-ffmpeg` package to a NixOS module, and then import this NixOS module into the NixOS configuration, see example here:

https://mynixos.com/pveierland/jellyfin-ffmpeg-test

Currently MyNixOS 1.0 is feature-locked and will not be updated further beyond content updates. In 2.0, all of the relevant mechanics are being changes in ways that should prevent this issue from occurring.
